### ISSUE TITLE
publish to pypi

### ISSUE THREAD

**Issue by raybellwaves** [intake-dynamodb/intake-dynamodb#2]
Hi,

I'm interested in publishing this to pypi.

I understand this hasn't been worked on for a while.

If there is interest i'm happy to help out. I've created https://github.com/intake-dynamodb which the repo can be transferred to if agreed. I can add existing members of @informatics-lab: @stevehadd, @kaedonkers and original author @jacobtomlinson as members of that organization.

**Comment by jacobtomlinson** [comment]
I think this has been done before for other projects in @informatics-lab. I expect @tam203 would need to give a thumbs up for this.

This is also a BSD-licenced project so forking it over there instead of transferring would be totally fine too.

I also don't think I would have time/interest in working on this these days, but you're more than welcome to add me if only in a bus factor reducing capacity.

**Comment by kaedonkers** [comment]
Hi @raybellwaves,
I can confirm that @tam203 and I are happy to transfer ownership, so long as the original authors and the Met Office Informatics Lab are acknowledged somehow.
If you're happy with this, how would you like to proceed?

**Comment by raybellwaves** [comment]
Thanks. I would say push anything to this repo regarding ownership e.g. to setup.py or however you would like to brand it according to other repos in the informatics-lab repos. You are then welcome to transfer it as I made you members of the intake-dynamodb org or I can. Thanks
